contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 2.3.2
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: |
  This playbook blocks malicious Domains using all integrations that are enabled.

  Supported integrations for this playbook:
  * Zscaler
  * Symantec Messaging Gateway
  * FireEye EX
  * Trend Micro Apex One
  * Proofpoint Threat Response
  * Cisco Stealthwatch Cloud
id: Block Domain - Generic v2
inputs:
- description: The Domain to block.
  key: Domain
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    The Domain List ID to add the Domain to.
    product: Proofpoint Threat Response
  key: DomainBlackListID
  playbookInputQuery: null
  required: false
  value: {}
name: Block Domain - Generic v2
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
      - "3"
      - "4"
      - "6"
      - "7"
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 806d142e-f679-48c3-8e95-1bbc49ace64a
      iscommand: false
      name: ""
      version: -1
    taskid: 806d142e-f679-48c3-8e95-1bbc49ace64a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 920,
          "y": 120
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: 1b928832-eb02-47c7-8aed-4a5248e72b7a
      iscommand: false
      name: Block Domain - Symantec Messaging Gateway
      playbookName: Block Domain - Symantec Messaging Gateway
      type: playbook
      version: -1
    taskid: 1b928832-eb02-47c7-8aed-4a5248e72b7a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 220,
          "y": 310
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      Domain:
        complex:
          root: inputs.Domain
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: 21ff4831-4836-424f-8aa7-e7b596743b91
      iscommand: false
      name: Block Domain - FireEye Email Security
      playbookName: Block Domain - FireEye Email Security
      type: playbook
      version: -1
    taskid: 21ff4831-4836-424f-8aa7-e7b596743b91
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 680,
          "y": 310
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      Domain:
        complex:
          root: inputs.Domain
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |-
        This playbook blocks domains using Zscaler.
        The playbook checks whether the Zscaler integration is enabled, whether the Domain input has been provided and if so, blocks the domain.
      id: 0cc3c7da-178a-4039-807e-d07f04c57ed8
      iscommand: false
      name: Block Domain - Zscaler
      playbookName: Block Domain - Zscaler
      type: playbook
      version: -1
    taskid: 0cc3c7da-178a-4039-807e-d07f04c57ed8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -240,
          "y": 310
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3c45a271-d018-4dfc-8673-429fb09bc06e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 3c45a271-d018-4dfc-8673-429fb09bc06e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 920,
          "y": 540
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: dc5cbc8e-0fdb-4833-8cc1-8ad26fc9e2f0
      iscommand: false
      name: Block Domain - Trend Micro Apex One
      playbookName: Block Domain - Trend Micro Apex One
      type: playbook
      version: -1
    taskid: dc5cbc8e-0fdb-4833-8cc1-8ad26fc9e2f0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1140,
          "y": 310
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: e8232ce9-4ce3-4342-8139-5bc01c3acb1b
      iscommand: false
      name: Block Domain - Proofpoint Threat Response
      playbookName: Block Domain - Proofpoint Threat Response
      type: playbook
      version: -1
    taskid: e8232ce9-4ce3-4342-8139-5bc01c3acb1b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 310
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        complex:
          root: inputs.Domain
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: 8e83a1ed-519c-44ae-8466-86207f1e0d31
      iscommand: false
      name: Block Domain - Cisco Stealthwatch
      playbookName: Block Domain - Cisco Stealthwatch
      type: playbook
      version: -1
    taskid: 8e83a1ed-519c-44ae-8466-86207f1e0d31
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 2050,
          "y": 310
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 485,
        "width": 2670,
        "x": -240,
        "y": 120
      }
    }
  }
